---
# Generated by the Woow Headscale add-on on every start.
# Manual edits are lost EXCEPT the DNS keys under `.dns.*` which are
# preserved across restarts by cont-init.d (see the "managed_paths" list).

server_url: "{{ .server_url }}"
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 0.0.0.0:9090
grpc_listen_addr: 127.0.0.1:50443
grpc_allow_insecure: false

noise:
  private_key_path: /var/lib/headscale/noise_private.key

prefixes:
  v4: "{{ .ipv4_prefix }}"
  v6: "{{ .ipv6_prefix }}"
  allocation: sequential

derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  paths: []
  auto_update_enabled: true
  update_frequency: 24h

disable_check_updates: true

node:
  expiry: 0
  ephemeral:
    inactivity_timeout: 30m

auto_update:
  enabled: false

trusted_proxies: []

database:
  type: sqlite
  sqlite:
    path: /var/lib/headscale/db.sqlite
    write_ahead_log: true

log:
  level: {{ .log_level }}
  format: text

policy:
  mode: file
  path: /etc/headscale/policy.json

# HANDOFF §7 #5: dns_records.json is Headplane-hot-reloaded and must NOT be
# rebuilt on every restart — see cont-init.d/headscale.sh for its bootstrap.
dns:
  magic_dns: true
  base_domain: "{{ .magic_dns_base_domain }}"
  override_local_dns: true
  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1
    split: {}
  search_domains: []
  extra_records_path: /etc/headscale/dns_records.json

unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"

logtail:
  enabled: false
