---
# Generated by the Woow Headscale add-on on every start.
# Manual edits are lost.
#
# HANDOFF §7 #2: Headplane v0.7.0 validates `integration.kubernetes.pod_name`
# even when disabled — DO NOT add an `integration.kubernetes:` section.
# `integration.proc` is required for SIGHUP reload of headscale in the same
# container and is safe to enable.

server:
  host: "0.0.0.0"
  port: 3000
  # base_url uses the server_url so cookies + redirects work out of the box
  # when the user is on the LAN. Change it if you reverse-proxy /admin.
  base_url: "{{ .server_url }}"
  # cookie_secret and cookie_secure are injected by cont-init.d
  cookie_secret: ""
  cookie_secure: false
  data_path: /var/lib/headscale/headplane

headscale:
  url: "http://127.0.0.1:8080"
  config_path: /etc/headscale/config.yaml
  dns_records_path: /etc/headscale/dns_records.json
  config_strict: true
  # api_key is injected by services.d/headplane/run after auto-provision
  api_key: ""

integration:
  proc:
    enabled: true
